import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider,useMessages  } from "next-intl";
import NextTopLoader from "nextjs-toploader";
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  const messages = useMessages()
  return (
    <NextIntlClientProvider locale={locale} messages={messages} >
      <html lang={locale} className="h-full">
        <body className={inter.className+' h-full bg-[#f4f5fa]'} >
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  );
}


// import type { Metadata } from "next";
// import { Inter , Poppins } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className="h-full">
//       <body className={inter.className+' h-full'}>{children}</body>
//     </html>
//   );
// }
